<?php
 $title = 'My building list';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p><a href="<?php echo $this->url('item', array(
         'action'=>'add'));?>">Add new building</a></p>


 <table class="table">
 <tr>
     <th>User</th>
     <th>Name</th>
     <th>Created</th>
     <th>Updated</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($items as $item): ?>
 <tr>
     <td>
         <a href="<?php echo $this->url('item',
             array('action'=>'edit', 'id' => $item->getId()));?>">
             <?php echo $this->escapeHtml($item->getTitle()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($item->getUser()); ?></td>
     <td><?php echo $this->escapeHtml($item->getName()); ?></td>
     <td><?php echo $this->escapeHtml($item->getCreated()); ?></td>
     <td><?php echo $this->escapeHtml($item->getUpdated()); ?></td>
     <td>
         <a href="<?php echo $this->url('item',
             array('action'=>'delete', 'id' => $item->getId()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>