<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Building\Module'                        => __DIR__ . '/Module.php',
    'Building\Controller\ItemController' => __DIR__ . '/src/Building/Controller/ItemController.php',
    'BuildingTest\Framework\TestCase'        => __DIR__ . '/tests/Building/Framework/TestCase.php',
    'BuildingTest\SampleTest'                => __DIR__ . '/tests/Building/SampleTest.php',
);
