<?php
$title = 'Edit building';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $url = $this->url('building', array('action' => 'edit', 'id' => '15'));
 $form->setAttribute('action', $url);
 $form->get('submit')->setAttribute('value', 'Edit');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('id')); 
 echo $this->formRow($form->get('user'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('created'));
 echo $this->formRow($form->get('updated'));
 ?>
 <div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
 <?php
 echo $this->form()->closeTag($form);