<?php
$title = 'Edit building';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
 	<tr>
     <?php
        $form = $this->form;
        $url = $this->url('building', array('action' => 'edit', 'id' => $id));
        $form->setAttribute('action', $url);
        $form->get('submit')->setAttribute('value', 'Edit');
        $form->prepare();
        ?>
         <td><?php echo $this->escapeHtml($building->getId()); ?></td>
         <td><?php echo $this->escapeHtml($building->getUser()); ?></td>
         <td>
         	<?php
         	echo $this->form()->openTag($form);
         	echo $this->formHidden($form->get('id'));
         	echo $this->formHidden($form->get('user'));
         	echo $this->formRow($form->get('name'));
         	echo $this->formHidden($form->get('created'));
         	echo $this->formHidden($form->get('updated'));
     	      ?>
         </td>
         <td><?php echo $this->escapeHtml($building->getCreated()); ?></td>
         <td><?php echo $this->escapeHtml($building->getUpdated()); ?></td>
	</tr>
 </table>
 <div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
 <?php
 echo $this->form()->closeTag($form);