<?php
 $title = 'My list of buildings';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p><a href="<?php echo $this->url('building', array(
         'action'=>'add'));?>">Add new building</a></p>


 <table class="table">
 <tr>
     <th>Id</th>
     <th>User</th>
     <th>Name</th>
     <th>Created</th>
     <th>Updated</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($buildings as $building): ?>
 <tr>
     <td><?php echo $this->escapeHtml($building->getId()); ?></td>
     <td><?php echo $this->escapeHtml($building->getUser()); ?></td>
     <td>
         <a href="<?php echo $this->url('building',
             array('action'=>'edit', 'id' => $building->getId()));?>">
             <?php echo $this->escapeHtml($building->getName()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($building->getCreated()); ?></td>
     <td><?php echo $this->escapeHtml($building->getUpdated()); ?></td>
     <td>
         <a href="<?php echo $this->url('building',
             array('action'=>'delete', 'id' => $building->getId()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>