<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Buildinglist\Module'                        => __DIR__ . '/Module.php',
    'Buildinglist\Controller\BuildingController' => __DIR__ . '/src/Buildinglist/Controller/BuildingController.php',
    'BuildinglistTest\Framework\TestCase'        => __DIR__ . '/tests/Buildinglist/Framework/TestCase.php',
    'BuildinglistTest\SampleTest'                => __DIR__ . '/tests/Buildinglist/SampleTest.php',
);
